# Generated by Django 3.1.1 on 2020-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50)),
                ('author', models.TextField(blank=True, max_length=50)),
                ('isbn_number', models.CharField(blank=True, max_length=50)),
                ('category', models.TextField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('loan', models.BooleanField(blank=True, max_length=20)),
                ('barCode', models.CharField(blank=True, max_length=20)),
                ('language', models.TextField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
