# Generated by Django 3.1.1 on 2020-09-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200927_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
