# Generated by Django 3.1.1 on 2020-09-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
